# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd015b19b774d89d683272c7dfbe672bd5862cbb36bac68c911b5f918ec9ac76b4559e2bacb1e2e5a229869a3b522b9a6a56ab2b15e9560d0ba3b2a88fc1e0ca

test:
  secret_key_base: 78894083f81cf4a2523c0a5185782ed5225ba4374803c817a76cd91c795401773660f9faad10ee168301aca868495a7e769d2b2a26c0c7fb458d3ba1cde0a621

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
